### ISSUE TITLE
node-lmdb.node has bad ELF magic

### ISSUE THREAD

**Issue by sOm2y** [Venemo/node-lmdb#130]
Hi team,
I'm trying put a node project into react native, everything was fine until this happened, I suspect I need rebuild node-lmdb native addon for android, but I tried to rebuild it with arch=arm but i still keep getting it, any idea know why?

```
05-15 01:22:36.041 6113-6206/com.nimiqpocketandroid E/NODEJS-MOBILE: /data/data/com.nimiqpocketandroid/files/nodejs-project/node_modules/@nimiq/jungle-db/node_modules/node-lmdb/node_modules/bindings/bindings.js:88
            throw e
            ^
    
    Error: dlopen failed: "/data/data/com.nimiqpocketandroid/files/nodejs-project/node_modules/@nimiq/jungle-db/node_modules/node-lmdb/build/Release/node-lmdb.node" has bad ELF magic
        at Object.Module._extensions..node (module.js:653:18)
        at Module.load (module.js:545:32)
        at tryModuleLoad (module.js:508:12)
        at Function.Module._load (module.js:500:3)
        at Module.require (module.js:568:17)
        at require (internal/module.js:11:18)
        at bindings (/data/data/com.nimiqpocketandroid/files/nodejs-project/node_modules/@nimiq/jungle-db/node_modules/node-lmdb/node_modules/bindings/bindings.js:81:44)
        at Object.<anonymous> (/data/data/com.nimiqpocketandroid/files/nodejs-project/node_modules/@nimiq/jungle-db/node_modules/node-lmdb/index.js:3:37)
        at Module._compile (module.js:624:30)
        at Object.Module._extensions..js (module.js:635:10)

**Comment by Venemo** [comment]
Hi @sOm2y thanks for reporting this. Please give me more details on what exactly you are trying to do and how to reproduce this issue.

**Comment by sOm2y** [comment]
@Venemo yes, running npm will generate node-gyp build for native addon, but i am generate it on mac which is intel architect. And that native addon build was for intel not android arm architect. So I guess I have to figure out a way to do that. From so far I discovered it's more a question for node-gyp instead of node-lmdb. 
Appreciate your reply tho.

**Comment by Venemo** [comment]
@sOm2y Good luck! Maybe open an issue at react native and maybe they can help you with this.
