### ISSUE TITLE
node-gyp rebuild error

### ISSUE THREAD

**Issue by NookieGrey** [Venemo/node-lmdb#134]
In process of installing I'm getting error:
```
 node-lmdb@0.6.0 install C:\Users\Nugzar\WebstormProjects\swap.react\node_modules\node-lmdb
> node-gyp rebuild


C:\Users\Nugzar\WebstormProjects\swap.react\node_modules\node-lmdb>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Pr
ogram Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Сборка проектов в этом решении по одному. Чтобы включить параллельную сборку, добавьте параметр "/m".
  mdb.c
  midl.c
..\dependencies\lmdb\libraries\liblmdb\mdb.c(932): warning C4146: unary minus operator applied to unsigned type, result still unsigned [C:\Users\Nugzar\WebstormProjects\swap.react\node_modules\node-lmdb\build\node-lmdb.vcxproj]
..\dependencies\lmdb\libraries\liblmdb\mdb.c(4195): warning C4244: '+=' : conversion from '__int64' to 'off_t', possible loss of data [C:\Users\Nugzar\WebstormProjects\swap.react\node_modules\node-lmdb\build\node-lmdb.vcxproj]
..\dependencies\lmdb\libraries\liblmdb\mdb.c(4687): warning C4996: 'GetVersion': was declared deprecated [C:\Users\Nugzar\WebstormProjects\swap.react\node_modules\node-lmdb\build\node-lmdb.vcxproj]
          C:\Program Files (x86)\Windows Kits\8.1\Include\um\sysinfoapi.h(110) : see declaration of 'GetVersion'
..\dependencies\lmdb\libraries\liblmdb\mdb.c(5710): warning C4244: 'return' : conversion from 'ssize_t' to 'int', possible loss of data [C:\Users\Nugzar\WebstormProjects\swap.react\node_modules\node-lmdb\build\node-lmdb.vcxproj]
..\dependencies\lmdb\libraries\liblmdb\mdb.c(5736): warning C4244: 'return' : conversion from 'ssize_t' to 'int', possible loss of data [C:\Users\Nugzar\WebstormProjects\swap.react\node_modules\node-lmdb\build\node-lmdb.vcxproj]
..\dependencies\lmdb\libraries\liblmdb\mdb.c(7715): warning C4146: unary minus operator applied to unsigned type, result still unsigned [C:\Users\Nugzar\WebstormProjects\swap.react\node_modules\node-lmdb\build\node-lmdb.vcxproj]
..\dependencies\lmdb\libraries\liblmdb\mdb.c(8292): warning C4333: '>>' : right shift by too large amount, data loss [C:\Users\Nugzar\WebstormProjects\swap.react\node_modules\node-lmdb\build\node-lmdb.vcxproj]
  node-lmdb.cpp
  env.cpp
  misc.cpp
  txn.cpp
  dbi.cpp
  cursor.cpp
..\src\misc.cpp(28): error C2146: syntax error : missing ';' before identifier 'uint32_t' [C:\Users\Nugzar\WebstormProjects\swap.react\node_modules\node-lmdb\build\node-lmdb.vcxproj]
..\src\misc.cpp(28): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\Users\Nugzar\WebstormProjects\swap.react\node_modules\node-lmdb\build\node-lmdb.vcxproj]
..\src\cursor.cpp(205): error C2065: 'constexpr' : undeclared identifier [C:\Users\Nugzar\WebstormProjects\swap.react\node_modules\node-lmdb\build\node-lmdb.vcxproj]
..\src\cursor.cpp(205): error C2143: syntax error : missing ';' before 'const' [C:\Users\Nugzar\WebstormProjects\swap.react\node_modules\node-lmdb\build\node-lmdb.vcxproj]
..\src\cursor.cpp(206): error C2065: 'argc' : undeclared identifier [C:\Users\Nugzar\WebstormProjects\swap.react\node_modules\node-lmdb\build\node-lmdb.vcxproj]
..\src\cursor.cpp(206): error C2078: too many initializers [C:\Users\Nugzar\WebstormProjects\swap.react\node_modules\node-lmdb\build\node-lmdb.vcxproj]
..\src\cursor.cpp(208): error C2065: 'argc' : undeclared identifier [C:\Users\Nugzar\WebstormProjects\swap.react\node_modules\node-lmdb\build\node-lmdb.vcxproj]
..\src\txn.cpp(312): error C2144: syntax error : 'double' should be preceded by ';' [C:\Users\Nugzar\WebstormProjects\swap.react\node_modules\node-lmdb\build\node-lmdb.vcxproj]
..\src\txn.cpp(312): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\Users\Nugzar\WebstormProjects\swap.react\node_modules\node-lmdb\build\node-lmdb.vcxproj]
..\src\txn.cpp(325): error C2144: syntax error : 'bool' should be preceded by ';' [C:\Users\Nugzar\WebstormProjects\swap.react\node_modules\node-lmdb\build\node-lmdb.vcxproj]
..\src\txn.cpp(325): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\Users\Nugzar\WebstormProjects\swap.react\node_modules\node-lmdb\build\node-lmdb.vcxproj]
..\src\txn.cpp(325): error C2086: 'int thread_local' : redefinition [C:\Users\Nugzar\WebstormProjects\swap.react\node_modules\node-lmdb\build\node-lmdb.vcxproj]
          ..\src\txn.cpp(312) : see declaration of 'thread_local'
c:\users\nugzar\webstormprojects\swap.react\node_modules\nan\nan_new.h(208): warning C4244: 'argument' : conversion from 'mdb_size_t' to 'double', possible loss of data (..\src\dbi.cpp) [C:\Users\Nugzar\WebstormProjects\swap.react\node_modules\node-lmdb\build\nod
e-lmdb.vcxproj]
          ..\src\dbi.cpp(260) : see reference to function template instantiation 'v8::Local<v8::Number> Nan::New<v8::Number,mdb_size_t>(A0)' being compiled
          with
          [
              A0=mdb_size_t
          ]
c:\users\nugzar\webstormprojects\swap.react\node_modules\nan\nan_new.h(208): warning C4244: 'argument' : conversion from 'mdb_size_t' to 'double', possible loss of data (..\src\env.cpp) [C:\Users\Nugzar\WebstormProjects\swap.react\node_modules\node-lmdb\build\nod
e-lmdb.vcxproj]
          ..\src\env.cpp(229) : see reference to function template instantiation 'v8::Local<v8::Number> Nan::New<v8::Number,mdb_size_t>(A0)' being compiled
          with
          [
              A0=mdb_size_t
          ]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Nugzar\WebstormProjects\swap.react\node_modules\node-lmdb
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN The package eosjs is included as both a dev and production dependency.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-lmdb@0.6.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-lmdb@0.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nugzar\AppData\Roaming\npm-cache\_logs\2018-08-15T14_23_16_036Z-debug.log
```

I'm work on windows 10 and have only installed Visual Studio 2013
Is it error with C++ library?

**Comment by Venemo** [comment]
If you want to use node-lmdb on Windows, please follow the steps outlined here: https://github.com/Venemo/node-lmdb#building-node-lmdb-on-windows

Let me know how it goes. If you have any problem following those steps, please post them here.

**Comment by Venemo** [comment]
@NugzarGaguliya Hi! Does this error still happen with the latest version?

**Comment by rraallvv** [comment]
I'm getting this error on macOS Mojave with node 13.1.0 and npm 6.12.1

```
$ npm i node-lmdb

> node-lmdb@0.7.0 install /Users/myuser/Desktop/tg-nim-tip-bot/node_modules/node-lmdb
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=13.1.0 runtime=node arch=x64 libc= platform=darwin)
  CC(target) Release/obj.target/node-lmdb/dependencies/lmdb/libraries/liblmdb/mdb.o
  CC(target) Release/obj.target/node-lmdb/dependencies/lmdb/libraries/liblmdb/midl.o
  CXX(target) Release/obj.target/node-lmdb/src/node-lmdb.o
  CXX(target) Release/obj.target/node-lmdb/src/env.o
../src/env.cpp:139:7: warning: field 'actions' will be initialized after field 'actionCount' [-Wreorder]
      actions(actions),
      ^
../src/env.cpp:141:7: warning: field 'putFlags' will be initialized after field 'env' [-Wreorder]
      putFlags(putFlags),
      ^
../src/env.cpp:166:13: warning: unused variable 'getCount' [-Wunused-variable]
        int getCount = 0;
            ^
../src/env.cpp:239:13: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
            resultsArray->Set(context, resultIndex, Nan::New<Number>(results[resultIndex]));
            ^~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/env.cpp:401:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
    obj->Set(context, Nan::New<String>("pageSize").ToLocalChecked(), Nan::New<Number>(stat.ms_psize));
    ^~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/env.cpp:402:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
    obj->Set(context, Nan::New<String>("treeDepth").ToLocalChecked(), Nan::New<Number>(stat.ms_depth));
    ^~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/env.cpp:403:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
    obj->Set(context, Nan::New<String>("treeBranchPageCount").ToLocalChecked(), Nan::New<Number>(stat.ms_branch_pages));
    ^~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/env.cpp:404:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
    obj->Set(context, Nan::New<String>("treeLeafPageCount").ToLocalChecked(), Nan::New<Number>(stat.ms_leaf_pages));
    ^~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/env.cpp:405:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
    obj->Set(context, Nan::New<String>("entryCount").ToLocalChecked(), Nan::New<Number>(stat.ms_entries));
    ^~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/env.cpp:429:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
    obj->Set(context, Nan::New<String>("mapAddress").ToLocalChecked(), Nan::New<Number>((uint64_t) envinfo.me_mapaddr));
    ^~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/env.cpp:430:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
    obj->Set(context, Nan::New<String>("mapSize").ToLocalChecked(), Nan::New<Number>(envinfo.me_mapsize));
    ^~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/env.cpp:431:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
    obj->Set(context, Nan::New<String>("lastPageNumber").ToLocalChecked(), Nan::New<Number>(envinfo.me_last_pgno));
    ^~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/env.cpp:432:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
    obj->Set(context, Nan::New<String>("lastTxnId").ToLocalChecked(), Nan::New<Number>(envinfo.me_last_txnid));
    ^~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/env.cpp:433:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
    obj->Set(context, Nan::New<String>("maxReaders").ToLocalChecked(), Nan::New<Number>(envinfo.me_maxreaders));
    ^~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/env.cpp:434:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
    obj->Set(context, Nan::New<String>("numReaders").ToLocalChecked(), Nan::New<Number>(envinfo.me_numreaders));
    ^~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/env.cpp:694:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
    exports->Set(Nan::GetCurrentContext(), Nan::New<String>("Env").ToLocalChecked(), envTpl->GetFunction(Nan::GetCurrentContext()).ToLocalChecked());
    ^~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16 warnings generated.
  CXX(target) Release/obj.target/node-lmdb/src/misc.o
../src/misc.cpp:34:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
    versionObj->Set(context, Nan::New<String>("versionString").ToLocalChecked(), Nan::New<String>(str).ToLocalChecked());
    ^~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/misc.cpp:35:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
    versionObj->Set(context, Nan::New<String>("major").ToLocalChecked(), Nan::New<Integer>(major));
    ^~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/misc.cpp:36:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
    versionObj->Set(context, Nan::New<String>("minor").ToLocalChecked(), Nan::New<Integer>(minor));
    ^~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/misc.cpp:37:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
    versionObj->Set(context, Nan::New<String>("patch").ToLocalChecked(), Nan::New<Integer>(patch));
    ^~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/misc.cpp:39:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
    exports->Set(context, Nan::New<String>("version").ToLocalChecked(), versionObj);
    ^~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/misc.cpp:45:46: error: no viable conversion from 'Local<v8::Context>' to 'v8::Isolate *'
    if (opt->IsBoolean() ? opt->BooleanValue(context).ToChecked() : defaultValue) {
                                             ^~~~~~~
/Users/myuser/Library/Caches/node-gyp/13.1.0/include/node/v8.h:2648:30: note: passing argument to parameter 'isolate' here
  bool BooleanValue(Isolate* isolate) const;
                             ^
../src/misc.cpp:249:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
    err.As<Object>()->Set(Nan::GetCurrentContext(), Nan::New("code").ToLocalChecked(), Nan::New(rc));
    ^~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/misc.cpp:285:11: warning: extra tokens at end of #endif directive [-Wextra-tokens]
    #endif;
          ^
          //
7 warnings and 1 error generated.
make: *** [Release/obj.target/node-lmdb/src/misc.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/myuser/.nvm/versions/node/v13.1.0/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/Users/myuser/.nvm/versions/node/v13.1.0/bin/node" "/Users/myuser/.nvm/versions/node/v13.1.0/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/myuser/Desktop/tg-nim-tip-bot/node_modules/node-lmdb
gyp ERR! node -v v13.1.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN tg-nim-tip-bot@1.0.0 No description
npm WARN tg-nim-tip-bot@1.0.0 No repository field.
npm WARN tg-nim-tip-bot@1.0.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-lmdb@0.7.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-lmdb@0.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/myuser/.npm/_logs/2019-11-12T05_12_38_654Z-debug.log
```

**Comment by Venemo** [comment]
Can you please check if version 0.8.0 fixes this issue?
