### ISSUE TITLE
Error: Invalid argument

### ISSUE THREAD

**Issue by Youhan** [Venemo/node-lmdb#137]
I am trying to run an example file:

`.../node-lmdb/examples$ node 1-env.js`

```
Current lmdb version is { versionString: 'LMDB 0.9.70: (December 19, 2015)',
  major: 0,
  minor: 9,
  patch: 70 }
.../node-lmdb/examples/1-env.js:11
env.open({
    ^

Error: Invalid argument
    at Object.<anonymous> (/node-lmdb/examples/1-env.js:11:5)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:499:15)
    at startMainThreadExecution (internal/bootstrap/node.js:436:3)
```

I am guessing that I have a problem with my environment!
Could you please help @Venemo ?

```
node -v
v11.7.0
npm -v
6.6.0
node-gyp -v
v3.8.0
```

**Comment by Venemo** [comment]
@Youhan Did you create the directory for the database?

**Comment by Youhan** [comment]
Yes, `testdata` is there. If it can't find the directory the error will say "Could not find the directory".

**Comment by Venemo** [comment]
Okay, I will take a look. I haven't used node-lmdb on newer node versions yet, so it is possible that there is a bug that prevents it from working properly.

**Comment by Venemo** [comment]
@Youhan Can you check if the latest version fixes it maybe?

**Comment by Youhan** [comment]
It is fixed.

Actually, I was running a [Homestead Vagrant box](https://app.vagrantup.com/laravel/boxes/homestead), it only was happening there.
No issues with other environments that I tested. ( MacOS and Ubuntu )

**Comment by Venemo** [comment]
@Youhan Glad to know. There was an issue that prevented compilation on node 10.x+, and I fixed that in the latest release. If you have any more problems, feel free to open another issue here.
