### ISSUE TITLE
node-gyp rebuild error

### ISSUE THREAD

**Issue by Andrew-Dyachenko** [Venemo/node-lmdb#197]
Hello, after updating the node to the 16th version of the gitlab for dockerfile launched in the pipeline, I began to receive this error. Then I tried to install this package directly on my computer under control of macOS and the error was confirmed.

Can you please push a patch for this issue?

```bash
andrey@ru41 client % npm i node-lmdb@latest  
npm ERR! code 1
npm ERR! path /Users/andrey/Sites/main-site/src/client/node_modules/node-lmdb
npm ERR! command failed
npm ERR! command sh -c node-gyp-build
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.13.0 | darwin | x64
npm ERR! gyp info find Python using Python version 3.10.0 found at "/Library/Frameworks/Python.framework/Versions/3.10/bin/python3"
npm ERR! (node:33516) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /Library/Frameworks/Python.framework/Versions/3.10/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/andrey/Sites/main-site/src/client/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/andrey/Sites/main-site/src/client/node_modules/node-lmdb/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/andrey/Sites/main-site/src/client/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/andrey/Library/Caches/node-gyp/16.13.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/andrey/Library/Caches/node-gyp/16.13.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/andrey/Sites/main-site/src/client/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/andrey/Library/Caches/node-gyp/16.13.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/andrey/Sites/main-site/src/client/node_modules/node-lmdb',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
npm ERR! 
npm ERR! No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
npm ERR! 
npm ERR! No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
npm ERR! 
npm ERR! Traceback (most recent call last):
npm ERR!   File "/Users/andrey/Sites/main-site/src/client/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1500, in XcodeVersion
npm ERR!     version_list = GetStdoutQuiet(["xcodebuild", "-version"]).splitlines()
npm ERR!   File "/Users/andrey/Sites/main-site/src/client/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1563, in GetStdoutQuiet
npm ERR!     raise GypError("Error %d running %s" % (job.returncode, cmdlist[0]))
npm ERR! gyp.common.GypError: Error 1 running xcodebuild
npm ERR! 
npm ERR! During handling of the above exception, another exception occurred:
npm ERR! 
npm ERR! Traceback (most recent call last):
npm ERR!   File "/Users/andrey/Sites/main-site/src/client/node_modules/node-gyp/gyp/gyp_main.py", line 51, in <module>
npm ERR!     sys.exit(gyp.script_main())
npm ERR!   File "/Users/andrey/Sites/main-site/src/client/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 670, in script_main
npm ERR!     return main(sys.argv[1:])
npm ERR!   File "/Users/andrey/Sites/main-site/src/client/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 662, in main
npm ERR!     return gyp_main(args)
npm ERR!   File "/Users/andrey/Sites/main-site/src/client/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 647, in gyp_main
npm ERR!     generator.GenerateOutput(flat_list, targets, data, params)
npm ERR!   File "/Users/andrey/Sites/main-site/src/client/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2451, in GenerateOutput
npm ERR!     writer.Write(
npm ERR!   File "/Users/andrey/Sites/main-site/src/client/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 831, in Write
npm ERR!     self.WriteSources(
npm ERR!   File "/Users/andrey/Sites/main-site/src/client/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1302, in WriteSources
npm ERR!     cflags = self.xcode_settings.GetCflags(
npm ERR!   File "/Users/andrey/Sites/main-site/src/client/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 661, in GetCflags
npm ERR!     archs = self.GetActiveArchs(self.configname)
npm ERR!   File "/Users/andrey/Sites/main-site/src/client/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 515, in GetActiveArchs
npm ERR!     xcode_archs_default = GetXcodeArchsDefault()
npm ERR!   File "/Users/andrey/Sites/main-site/src/client/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 122, in GetXcodeArchsDefault
npm ERR!     xcode_version, _ = XcodeVersion()
npm ERR!   File "/Users/andrey/Sites/main-site/src/client/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1511, in XcodeVersion
npm ERR!     version = CLTVersion()  # macOS Catalina returns 11.0.0.0.1.1567737322
npm ERR!   File "/Users/andrey/Sites/main-site/src/client/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1549, in CLTVersion
npm ERR!     return re.search(regex, output).groupdict()["version"]
npm ERR! AttributeError: 'NoneType' object has no attribute 'groupdict'
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/andrey/Sites/main-site/src/client/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 20.6.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/Users/andrey/Sites/main-site/src/client/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /Users/andrey/Sites/main-site/src/client/node_modules/node-lmdb
npm ERR! gyp ERR! node -v v16.13.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andrey/.npm/_logs/2021-11-23T10_31_00_682Z-debug.log
```

**Comment by kriszyp** [comment]
Ok, I am a bit confused, as these are different errors, but more importantly, different packages. The first error looks like it is for lmdb-store (different package/repo) and the second error is for node-lmdb (don't worry, I maintain lmdb-store too, I'll still help you, just want to make sure I am properly understanding where the error is). Do you know what version of lmdb-store you were trying to install in the first version? The latest version should have prebuilds for linux-x64+node-v17 (so it shouldn't need to compile at all). Also, the root error is "Operation not permitted". Is it possible that there is an existing process running with the package you are installing/upgrading over?

The second error is for node-lmdb building on mac, and looks like some mac compiler error unrelated to node-lmdb. I could add some prebuilds for macos for node-lmdb, and that would probably resolve that issue. However, I doubt that would have any effect on the first issue since it looks like it is probably unrelated.

**Comment by Andrew-Dyachenko** [comment]
Yes these are different errors. The first one is the original place where I have seen this at the first time. This is the GitLab's pipeline which is running on some kind of Linux in a Docker environment. Until this moment I even did not know that this project have using `node-lmdb` package. I don't know what explicitness version of `node-lmdb` package version GitLab's pipeline is trying to install in the first error case. I triend to find what package in this project depends on it, but didn't find it:

```bash
andrey@ru41 client % npm ls node-lmdb
main-site@1.17.0 /Users/andrey/Sites/main-site/src/client
└── (empty)

andrey@ru41 client %
```

Than I tried to install `node-lmdb` package with command `npm i node-lmdb@latest` to simulate this issue on my local machine in a macOS to get more experience about this issue.

Fortunately, I managed to skip this problem and assemble the GitLab's pipeline by replacing it in Dockerfile:

```yaml
RUN npm i --no-optional
```
to
```yaml
RUN npm ci --no-optional
```

but this is just walkaround...

Yes please if you can do routine job like prebuilds for macOS/Linux/Windows to reduce potential assembly issue it will be wonderfull!

**Comment by kriszyp** [comment]
But the package you referenced is lmdb-store. I don't think using `npm ls node-lmdb` will find lmdb-store, you need to type `npm ls lmdb-store`? And updating node-lmdb won't fix your lmdb-store issue, right?

**Comment by Andrew-Dyachenko** [comment]
You are right!
```bash
andrey@ru41 client % npm ls lmdb-store
main-site@1.17.0 /Users/andrey/Sites/main-site/src/client
└─┬ @parcel/packager-xml@2.0.1
  └─┬ @parcel/types@2.0.1
    └─┬ @parcel/cache@2.0.1
      └── lmdb-store@1.6.14

andrey@ru41 client % 
```

**Comment by Andrew-Dyachenko** [comment]
To build the project, I actively use [Parcel](https://parceljs.org/), which most likely depends on `lmdb-store` and `node-lmdb`

**Comment by kriszyp** [comment]
Yes, lmdb-store is a dependency of parcel. lmdb-store@1.6.14 already includes a prebuild for linux-x64+node-v16 (you could verify it at node_modules/lmdb-store/prebuilds/linux-64/node-abi94.node). So the prebuild must somehow be failing to work on your linux system. Are you using a published dockerfile? I'd be glad to try to run a github action to see if I could reproduce this on the same docker container you are using.

**Comment by Andrew-Dyachenko** [comment]
> Yes, lmdb-store is a dependency of parcel. lmdb-store@1.6.14 already includes a prebuild for linux-x64+node-v16 (you could verify it at node_modules/lmdb-store/prebuilds/linux-64/node-abi94.node). So the prebuild must somehow be failing to work on your linux system. Are you using a published dockerfile? I'd be glad to try to run a github action to see if I could reproduce this on the same docker container you are using.
> 
> (And if you don't mind, we could file/move this to [lmdb-store](https://github.com/DoctorEvidence/lmdb-js), just for better organization)

Sure! We can move this issue to more appropriate place.

**Comment by Andrew-Dyachenko** [comment]
Can we automatically move this issue to [lmdb-store](https://github.com/DoctorEvidence/lmdb-js)?

**Comment by kriszyp** [comment]
Github gives a 500 error when I try to transfer the issue, so I guess that won't work right now.

**Comment by Andrew-Dyachenko** [comment]
Good. Maybe a little later it will turn out to be move this issue to [lmdb-store](https://github.com/DoctorEvidence/lmdb-js) automatically

**Comment by kriszyp** [comment]
Well, I was just going to try to run the current lmdb-store test suite github action using your docker file.

Another thing that would be a helpful for debugging would be for you to try to run your build with `npm i --ignore-scripts`. This should force it to use the prebuilds and not attempt any compilation, and should then eventually show/report if and what error is occurring in the prebuilds.

**Comment by kriszyp** [comment]
So I ran this github action, which I think should be a close resemblance of your docker configuration, but specifically building and testing lmdb-store:
https://github.com/DoctorEvidence/lmdb-js/runs/4301924530?check_suite_focus=true
The build succeeded and lmdb-store ran, however, the test suite completely failed due to permission denied errors on any attempt to create the db files. I realize this isn't exactly the same error you were seeing, however, this is an error I have never seen before on any of the other dockers I have run/tested lmdb-store on, and it seems similar and possibly the same cause as your errors. I did some comparisons and it seems this permissions issue manifests specifically for the alpine node 16 docker images, but not for alpine node 12 or 14. I don't know if there was a change to these docker image that altered the permissions?

Can you try a couple things for me:
- Can you see if your error still occurs with a node 14 image (node:14-alpine3.14)? (probably have to update your package.json to allow that node version). Naturally I still want to try to get this working with node 16, but just curious if it is related to this permission difference.
- Can you see if the error still occurs if you use `npm i --ignore-scripts`?

Thank you for the help!

**Comment by Andrew-Dyachenko** [comment]
About things you are asking for:

- It was after the transition from the **14th** version Node to the **16th** version Node that this error began to occur. I can try to test this again but at the moment it will require switching to yarn since the project I'm working on uses file: a link to a local package that only works from **NPM 7** and up that comes with Node **15th** and up ... When installing using yarn, the package installation logic falls on yarn and the error may not occur, but this is not certain.
- Fun fact: In the context of the **16th** version of the Node and, accordingly, **NPM 8**, I tried to cause an error by changing in the Dockerfile the `npm ci` command to `npm i` and started the build process in the gitlab pipeline, but the error did not return 🤷‍♂️. The build completed successfully. Than I tryed to change in the Dockerfile `npm i --no-optional` command to `npm i --ignore-scripts` and again started the build process in the gitlab pipeline, but the build is still successfull. I could not throw the previous error again 🤷‍♂️.

```bash
Step 20/43 : RUN npm i --ignore-scripts
 ---> Running in 1c51af6be1d7
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated @babel/polyfill@7.4.4: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
added 1149 packages, and audited 1152 packages in 36s
194 packages are looking for funding
  run `npm fund` for details
19 moderate severity vulnerabilities
To address all issues (including breaking changes), run:
  npm audit fix --force
Run `npm audit` for details.
Removing intermediate container 1c51af6be1d7
```

**Comment by kriszyp** [comment]
Ok, I also tried using `npm ci` instead of `npm i` in my github action, but still no luck in reproducing an error.

**Comment by Andrew-Dyachenko** [comment]
Yes, the error no longer occurs. Reason not found
