### ISSUE TITLE
Build with node-gyp build

### ISSUE THREAD

**Issue by jahewson** [Venemo/node-lmdb#5]
In the readme it says to build with:

```
node-gyp configure
make -C build -j4
```

But this really should be:

```
node-gyp configure
node-gyp build
```

What are the `-C` and `-j4` flags doing?

**Comment by drakiula** [comment]
when running node-gyp configure on Windows 7 Pro X64, I am getting the following:
$ node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.0
gyp info using node@7.8.0 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\IBM_ADMIN\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\SRC\\GO_WORK\\src\\github.com\\drakiula\\node-lmdb\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\IBM_ADMIN\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\IBM_ADMIN\\.node-gyp\\7.8.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\IBM_ADMIN\\.node-gyp\\7.8.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\IBM_ADMIN\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\SRC\\GO_WORK\\src\\github.com\\drakiula\\node-lmdb',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\SRC\\GO_WORK\\src\\github.com\\drakiula\\node-lmdb\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File "C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2006, in GenerateOutput
    generator_flags))
  File "C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 943, in _GenerateProject
    return _GenerateMSBuildProject(project, options, version, generator_flags)
  File "C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 3311, in _GenerateMSBuildProject
    extension_to_rule_name)
  File "C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2063, in _GenerateMSBuildFiltersFile
    easy_xml.WriteXmlIfChanged(content, filters_path, pretty=True, win32=True)
  File "C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\easy_xml.py", line 134, in WriteXmlIfChanged
    f = open(path, 'w')
**IOError: [Errno 13] Permission denied: 'D:\\SRC\\GO_WORK\\src\\github.com\\drakiula\\node-lmdb\\build\\node-lmdb.vcxproj.filters'**
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\IBM_ADMIN\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd D:\SRC\GO_WORK\src\github.com\drakiula\node-lmdb
gyp ERR! node -v v7.8.0
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok

Is this

**Comment by Venemo** [comment]
@drakiula Please try again and if the issue is still there, please open a new issue.
